sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - cat ~/.m2/settings.xml
before_script:
  - cd src
script:
  - mvn -B -U -T2 -fae -Prelease clean install -Dtest.maxHeapSize=512M -Djava.awt.headless=true
notifications:
  email:
    on_success: never
    on_failure: never
jdk: oraclejdk8
